### ISSUE TITLE
Restic + Storj

### ISSUE THREAD

**Issue by krystek17** [Gigahawk/nixos-config#1]
Hi, I have noticed that you have created a module that integrates both storj and restic, which is exactly what I'm looking for ^^.

I have the following questions regarding your config:

- There is no configuration for rclone, does it mean that it can be configured without rclone?
- How did you write the repository path? Is the following path correct "rclone:storj:<bucket_name>/<folder_name>"?
- Regarding the environment file where I supposed your credentials are stored, are you using access grant, s3 credentials or API ? 

Thanks in advance

Krystek

**Comment by Gigahawk** [comment]
I'm just using Storj as an S3 compatible backend, which restic supports natively without rclone
Here are excerpts of my secret files for reference.

environment:
```
AWS_ACCESS_KEY_ID=xxxx
AWS_SECRET_ACCESS_KEY=xxxx
```

password:
```
long list of words
```

repository:
```
s3:https://gateway.storjshare.io/xxxx
```
